name = "Jinja"
grammar = "jinja"
path_suffixes = ["jinja", "jinja2", "j2"]
block_comment = { start = "{#", prefix = "", end = "#}", tab_size = 0 }
brackets = [
  { start = "{{", end = "}}", close = true, newline = false },
  { start = "{%", end = "%}", close = true, newline = false },
  { start = "{#", end = "#}", close = true, newline = false },
]
